PANEL_DIRECTORY=/var/www/pterodactyl
NODE_NAME=NODE-01
NODE_DESCRIPTION=NODE BY ZXVCODE
NODE_LOCATION=Jakarta
NODE_SSL=n
NODE_PROXY=n
ALLOCATION_IP=0.0.0.0
ALLOCATION_START=2000
ALLOCATION_END=2500
DAEMON_PORT=8080
SFTP_PORT=2022
ACCESS_KEY=ZxvHost
